audit_header: false
title: -- MARKET -- Mortgage Video Blog with -- CLIENT NAME --
description: Our mission at -- CLIENT BRAND -- is to be your best resource for the -- MARKET -- mortgage process. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND --, your professional Mortgage Loan Originator.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Dean Adler
  title: Mortgage Loan Originator
  license_number: NMLS 110615
  about_markdown: |
    Dean Adler, is a former City of Miami Beach Police Officer that retired after an on-the-job injury. Dean is currently a Loan Originator at PRMG, Inc. in Sunrise, Florida, specializing in residential purchases and refinances for Law Enforcement Officers, Firefighters, Veterans, Civilians and their families. He has been in the mortgage industry for over 25 years in the South Florida area.
  brand: Paramount Residential Mortgage Group, Inc.
  brokerage:
  market: Miami
  address:
  phone: 954-649-2960
  phone_type:
  phone2:
  phone2_type:
  email: DAdler@PRMG.net
  url: http://DeanAdler.com

CTAs:
  first_CTA_text: Contact
  first_CTA_URL: https://deanadler.com/contact-us/
  second_CTA_text: Mortgage Calculator
  second_CTA_URL: https://deanadler.com/mortgage-basics/mortgage-calculator/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Mortgage Basics"
    CTA_text: "Find out how much you can afford."
    CTA_link_text: "Mortgage Calculator"
    CTA_url: https://deanadler.com/mortgage-basics/mortgage-calculator/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Contact Us today"
    CTA_text2: "Dean Adler, NMLS 110615 Loan Originator at Bankers Mortgage Lending"
    CTA_link_text2: "Contact"
    CTA_url2: https://deanadler.com/contact-us/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/DeanAdlerTeam/
  linkedin_url:
  youtube_url:
  twitter_url: https://twitter.com/deanadlerteam
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: 
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#0000CD'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
