audit_header: false
title: Miami Mortgage Video Blog with Dean Adler
description: Our mission at Hamilton Group Funding is to be your best resource for the -- MARKET -- mortgage process. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from Hamilton Group Funding, your professional Mortgage Loan Originator.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Dean Adler
  title: Mortgage Loan Originator
  license_number: NMLS 110615
  about_markdown: |
    Dean Adler has been a South Florida resident since 1973, originally residing in Miami-Dade County, then moving to Broward County over 30 years ago.
    In the 1980’s Dean became the youngest Police Officer for the City of Miami Beach at age 19, ultimately retiring early due to an on-the-job injury.
    Dean is currently a Mortgage Loan Originator with Paramount Residential Mortgage Group, Inc. (PRMG) in Sunrise, Florida specializing in residential purchases and refinances.  He focuses on his Law Enforcement roots through relationships with Police Officers, Firefighters, Veterans and their family members.
    With over 25 years of experience, closing well over 2,000 mortgages, Dean and his support staff have the knowledge to guide you through the entire loan process.
    So whether you’re purchasing or refinancing your home or if you need the assistance of one of Dean’s top real estate agent partners, call him today.
    Deal With Someone You Can Trust!
  brand: Hamilton Group Funding
  brokerage:
  market: Miami
  address:
  phone: 954-649-2960
  phone_type:
  phone2:
  phone2_type:
  email: Dean.Adler@HGFloans.com
  url: http://DeanAdler.com

CTAs:
  first_CTA_text: Contact
  first_CTA_URL: https://deanadler.com/contact-us/
  second_CTA_text: Apply Now
  second_CTA_URL: /apply-now/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Mortgage Application"
    CTA_text: 'Please complete the Mortgage Pre-Approval Application and email to <a href="mailto:Dean.Adler@HGFloans.com">Dean.Adler@HGFloans.com</a>.  If you have any questions, please call us at <a href="1-954-649-2960">954-649-2960</a>.'
    CTA_link_text: "Apply Now"
    CTA_url: /apply-now/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Contact Us today"
    CTA_text2: "Dean Adler, NMLS 110615 Loan Originator at PRMG, Inc."
    CTA_link_text2: "Contact"
    CTA_url2: https://deanadler.com/contact-us/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/DeanAdlerTeam/
  linkedin_url: https://www.linkedin.com/in/dean-adler-7b527823/
  youtube_url: https://www.youtube.com/channel/UCnK3yh8tJNsmhquIjSTUj2w?
  twitter_url: https://twitter.com/deanadlerteam
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://podcasts.apple.com/us/podcast/miami-real-estate-podcast-with-dean-adler/id1480264217

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Hamilton Group Funding - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 50
  hero_text:
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#772f40'
  theme_color: '#231f20'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
